[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "always"
# healthcheck اختیاری - اگر پنل هنوز بالا نیومده خطا نده
# healthcheckPath = "/"
# healthcheckTimeout = 100
